trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore 🔃
  inputs:
    command: 'restore'
    projects: '$(solution)'
  
- task: DotNetCoreCLI@2
  displayName: Build 🏗️
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: Test 🧪
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-build'

- task: DotNetCoreCLI@2
  displayName: 🏭 Pack NuGets
  inputs:
    command: pack
    packagesToPack: '**/FireConfig.csproj'
    configuration: $(buildConfiguration)
    nobuild: true
    verbosityPack: Normal

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'a6a04245-951b-4ff2-8918-d887b5c75d49'